version: 2.28.{build}
branches:
  only:
  - /master/
image: Visual Studio 2017
configuration: Release
platform: x86
before_build:
- cmd: >-
    git submodule init

    git submodule update
build:
  project: UnifyZip.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: $(Configuration)
  name: uz$(APPVEYOR_BUILD_VERSION)
